---
- name: provision cloud nodes
  hosts: localhost
  connection: local

  # digital ocean creds are kept in the private repo
  vars_files:
  - $private/vars.yml

  tasks:

  # Use the digital ocean module to spin up cloud nodes.
  - name: Provision buttermilk if necessary
    digital_ocean: >
      state=active
      name=buttermilk
      ssh_key_ids=threebean
      size_id=66
      region_id=4
      image_id=696598
      wait_timeout=500
      client_id={{ do_client_id }}
      api_key={{ do_api_key }}
      unique_name=true
    register: buttermilk

  - name: Print out node info
    debug: msg={{ buttermilk.droplet.ip_address }}

- name: Set up buttermilk content and config
  hosts: buttermilk

  vars_files:
  - $private/vars.yml

  roles:
  - common
  - server
  - irc-bouncer
  - task-server
