# Use the digital ocean module to spin up cloud nodes.
- name: playbook | provision | Provision buttermilk if necessary
  digital_ocean: >
    state=active
    name=buttermilk
    ssh_key_ids=threebean
    size_id=66
    region_id=4
    image_id=696598
    wait_timeout=500
    client_id={{ do_client_id }}
    api_key={{ do_api_key }}
    unique_name=true
  register: buttermilk

- name: playbook | provision | Provision compute01 if necessary
  digital_ocean: >
    state=active
    name=compute01
    ssh_key_ids=36649
    size_id=66
    region_id=4
    image_id=696598
    wait_timeout=500
    client_id={{ do_client_id }}
    api_key={{ do_api_key }}
    unique_name=true
  register: compute01

- name: playbook | provision | add buttermilk to dynamic inventory
  add_host: >
      name=buttermilk
      groups=dynamic,servers,bouncer,task-server
      ansible_ssh_host={{ buttermilk.droplet.ip_address }}
      ansible_ssh_user=root

- name: playbook | provision | add compute01 to dynamic inventory
  add_host: >
      name=compute01
      groups=dynamic,servers,compute,nagios
      ansible_ssh_host={{ compute01.droplet.ip_address }}
      ansible_ssh_user=root
