# Use the digital ocean module to spin up cloud nodes.
# TODO -- use host_vars, group_vars and looping over 'dynamic' to automate this
- name: playbook | provision | Provision buttermilk if necessary
  digital_ocean: >
    state=active
    name=buttermilk
    ssh_key_ids=36649
    size_id=66
    region_id=4
    image_id=6370882
    wait_timeout=500
    client_id={{ do_client_id }}
    api_key={{ do_api_key }}
    unique_name=true

- name: playbook | provision | Provision compute01 if necessary
  digital_ocean: >
    state=active
    name=compute01
    ssh_key_ids=36649
    size_id=66
    region_id=4
    image_id=6370882
    wait_timeout=500
    client_id={{ do_client_id }}
    api_key={{ do_api_key }}
    unique_name=true
