- name: reboot
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: True

- name: wait for ssh to become available again
  local_action: wait_for host={{inventory_hostname}} port={{ ansible_ssh_port }} state=started
  sudo: false
