- name: reboot the host one minute from now.
  command: shutdown -r +1 "Ansible restarting this beast"
  async: 0
  poll: 0
  ignore_errors: True

- name: wait for the host to go down
  wait_for:
      host: "{{inventory_hostname}}"
      port: 22
      state: stopped
  delegate_to: localhost
  sudo: false

- name: wait for the host to come back up
  wait_for:
      host: "{{inventory_hostname}}"
      port: 22
      state: started
  delegate_to: localhost
  sudo: false
