
- name: Check if Firefox is installed
  stat:
      path: /usr/bin/firefox
  register: firefox
  tags:
    - security
    - firefox


- name: Install Firefox security extensions
  dnf:
      name: "{{ item }}"
      state: present
  with_items:
      - mozilla-noscript
      - mozilla-https-everywhere
      - mozilla-adblockplus
  when: firefox.stat.exists
  tags:
    - security
    - firefox
