- name: fprintd | Remove the fingerprint reader service
  dnf:
      name: libfprint
      state: absent
  tags:
  - security
  - auth
  - fingerprint

- name: fprintd | Install authconfig
  dnf:
      name: authconfig
      state: present
  tags:
  - security
  - auth
  - fingerprint

- name: fprintd | Update the pam system-auth configuration
  command: /usr/sbin/authconfig --disablefingerprint --update
  changed_when: False
  tags:
  - security
  - auth
  - fingerprint
