- include: packages.yml
- yum: name=ntp state=present
- service: name=ntpd state=started enabled=yes
- include: rkhunter.yml
- include: lynis.yml
- include: selinux.yml
- include: firewalld.yml
- include: dnssec.yml
- include: yum.yml
- include: sudo.yml
- include: sshd.yml
- include: fprintd.yml
- include: suricata.yml
