- include: packages.yml
- dnf:
      name: ntp
      state: present
- service: name=ntpd state=started enabled=yes
- include: rkhunter.yml
- include: lynis.yml
- include: selinux.yml
- include: firewalld.yml
- include: dnssec.yml
- include: yum.yml
- include: sudo.yml
- include: sshd.yml
- include: fprintd.yml
- include: suricata.yml
- include: firefox.yml

# Ignore fail2ban for now until I have a good way to whitelist myself.  I keep
# getting banned when ansible "waits for ssh to come back" because it just
# tries to ssh over and over again... and gets banned.
#- include: fail2ban.yml

# Lock down ipv6 when ipv6 is available
- include: ipv6.yml
  when: "ansible_default_ipv6 != {}"
