- name: Enable the updates-testing repository
  copy:
      src: fedora-updates-testing.repo
      dest: /etc/yum.repos.d/fedora-updates-testing.repo

- name: Common | update all packages
  dnf:
      state: latest
      name: "*"

- name: See if any updated packages need restarting
  command: /usr/bin/needs-restarting
  changed_when: False
  register: needs_restarting

- name: Pause before rebooting
  pause:
      prompt: "We need to restart for the updates to take effect"
  when: needs_restarting.stdout and dont_pause_before_reboot is not defined

- name: Reboot for updated packages
  include: "{{ tasks }}/reboot.yml"
  when: needs_restarting.stdout
