# file: roles/security/tasks/rkhunter.yml

- name: Security | rkhunter | Make sure rkhunter is installed and up to date
  dnf:
      name: rkhunter
      state: present
  tags:
    - security
    - rkhunter
