- name: Ensure Installed - policycoreutils
  yum: pkg=policycoreutils state=latest

- name: Ensure Installed - policycoreutils-python
  yum: pkg=policycoreutils-python state=latest

- name: SELinux Enforcing (Targeted)
  selinux: policy=targeted state=enforcing
  register: selinux_result

- name: Reboot to enable selinux if necessary
  include: "{{ tasks }}/reboot.yml"
  when: selinux_result|changed
