- name: sudo | ensure that we are a member of the wheel group
  user:
      name: "{{ username }}"
      groups: wheel
      append: yes
  tags:
  - security
  - sudo


- name: sudo | allow wheel with a password
  lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) ALL'
  tags:
  - security
  - sudo


- name: Copy /etc/sudoers.d/ssh_auth_sock into place
  copy:
      content: 'Defaults env_keep += "SSH_AUTH_SOCK"\n'
      dest: '/etc/sudoers.d/ssh_auth_sock'
      #validate: 'visudo -cf %s'
      owner: root
      group: root
      mode: 0440
  tags:
    - security
    - sudo

- name: sudo | disable the need for a tty to enable ansible ssh pipelining
  copy:
      content: 'Defaults !requiretty\n'
      dest: '/etc/sudoers.d/norequiretty'
      #validate: 'visudo -cf %s'
      owner: root
      group: root
      mode: 0440
  tags:
  - security
  - sudo
