- name: Include some packages
  dnf:
      name: "{{ item }}"
      state: present
  with_items:
  - mosh
  - NetworkManager-vpnc
  - rubygem-rhc
  - ansible
  - python-dopy
  - python-boto
  tags:
  - jumpoff

- name: Synchronize some scripts to /usr/local/bin
  synchronize:
      src: bin/
      dest: /usr/local/bin/
  tags:
  - jumpoff

- seboolean: name=mozilla_plugin_use_bluejeans persistent=yes state=yes
  tags:
  - jumpoff
  - selinux
