- name: install common packages
  dnf:
      state: present
      name: "{{ item }}"
  with_items:
  - weechat
  - bitlbee
  - tmux
  tags:
  - packages
  - irc

- name: Copy weechat config with rsync
  synchronize:
      src: weechat/
      dest: "/home/{{username}}/.weechat/"
  tags: irc

- name: Copy weechat config template directly
  template:
      src: irc.conf
      dest: "/home/{{ username }}/.weechat/irc.conf"
      owner: "{{ username }}"
  tags: irc

- name: Set bitlbee to start
  service:
      name: bitlbee
      state: started
      enabled: yes
  tags: irc

- name: Copy in a tmux systemd service file
  copy:
      src: tmux-service
      dest: "/usr/lib/systemd/system/tmux@{{username}}.service"
  notify: reload systemd service files
  tags: irc

- name: Set that tmux session to start
  service:
      name: "tmux@{{username}}"
      state: started
      enabled: yes
  tags: irc
