- name: install s3cmd
  yum: pkg=s3cmd state=present

- name: copy s3 config
  template: src=s3cfg dest=/root/.s3cfg

- name: add a cronjob to backup
  template: src=s3-cronjob dest=/etc/cron.d/s3-backup-{{name}}
