- name: Include some packages
  yum: name={{ item }} state=present
  with_items:
  - git
  - hub
  - python-virtualenvwrapper
  - pkgwat
  - python-pip
  - gcc
  - gcc-c++
  - libcurl-devel
  tags:
  - development

- name: Synchronize some scripts to /usr/local/bin
  synchronize: src=bin/ dest=/usr/local/bin/
  tags:
  - development
