- name: Include some packages
  yum: name={{ item }} state=present
  with_items:
  - git
  - gitflow
  - hub
  - python-virtualenvwrapper
  - python-pip
  - gcc
  - gcc-c++
  - libcurl-devel
  - hovercraft
  - libffi-devel
  - zeromq-devel
  - pkgwat
  - fedpkg
  - fedora-packager
  - redhat-rpm-config
  tags:
  - development

- name: Synchronize some scripts to /usr/local/bin
  synchronize: src=bin/ dest=/usr/local/bin/
  tags:
  - development
