- name: Server | install server packages
  yum:
      state: present
      name: "{{ item }}"
  with_items:
  - mosh
  - firewalld
  tags:
  - packages

- name: Server | open some ports for mosh
  firewalld:
      port: "{{ item }}/udp"
      state: enabled
      permanent: true
      zone: public
  with_items:
      - 60000
      - 60001
      - 60002
      - 60003
      - 60004
  notify:
    - restart firewalld

- name: Server | users | give {{ username }} an ssh key
  authorized_key:
    user: "{{ username }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
