- name: Server | install server packages
  yum: state=present name=$item
  with_items:
  - mosh
  tags:
  - packages

- name: Server | users | give $username an ssh key
  authorized_key: >
    user=$username
    key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
