---


- name: system configuration (packages, etc...)
  hosts: geier

  vars_files:
  - vars/global.yml

  roles:
  - common
  - security
  - gnome/system
  - flash
  - jumpoff
  - development
  - task/client
  - rss/client
  - role: mail/client
    user: threebean

- name: basics for the gnome user (shortcuts, etc..)
  hosts: geier
  su: yes
  su_user: threebean

  vars_files:
  - vars/global.yml

  roles:
  - role: gnome/user
    # Override the gpg settings for me with a longer timeout
    gpg_gsettings:
    - key: gpg-cache-method
      value: 'timeout'
      schema: org.gnome.crypto.cache
    - key: gpg-cache-ttl
      # 2100 seconds is 35 minutes
      value: 2100
      schema: org.gnome.crypto.cache


# TODO -- two things not covered:
# - ssh config, including the list of proxy commands
# - gpg config, which doesn't really have anything in it anyways
