- name: provision cloud nodes
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
  - vars/global.yml

  tasks:
  - include: private.yml
  - include: "{{ tasks }}/provision.yml"

# For some reason this is broken now... it was nice to have.
#- name: setup a local /etc/hosts
#  hosts: localhost
#  connection: local
#  user: root
#
#  vars_files:
#  - vars/global.yml
#
#  tasks:
#  - include: "{{ tasks }}/record_hosts.yml"
