---
- name: playbook | provision | provision cloud nodes
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
  - vars/global.yml

  tasks:
  - include: private.yml
  - include: "{{ tasks }}/provision.yml"
  - name: dns | set up dns for fml.threebean.net
    route53: >
        aws_access_key={{ aws_access_key.secret }}
        aws_secret_key={{ aws_secret_key.secret }}
        command=create
        overwrite=yes
        zone=threebean.net
        record=fml.threebean.net
        type=A
        value={{hostvars.computer01.ansible_ssh_host}}
  - name: dns | set up dns for badges.threebean.net
    route53: >
        aws_access_key={{ aws_access_key.secret }}
        aws_secret_key={{ aws_secret_key.secret }}
        command=create
        overwrite=yes
        zone=threebean.net
        record=badges.threebean.net
        type=A
        value={{hostvars.computer01.ansible_ssh_host}}
  - name: dns | set up dns for tw2-demos.threebean.net
    route53: >
        aws_access_key={{ aws_access_key.secret }}
        aws_secret_key={{ aws_secret_key.secret }}
        command=create
        overwrite=yes
        zone=threebean.net
        record=tw2-demos.threebean.net
        type=A
        value={{hostvars.computer01.ansible_ssh_host}}

- name: playbook | site | Set up security
  hosts: dynamic
  vars_files:
  - vars/global.yml
  roles:
  - role: security

- name: playbook | site | Set up basic server config
  hosts: dynamic
  vars_files:
  - vars/global.yml
  roles:
  - role: common
  - role: server

- name: playbook | site | Set up nagios head
  hosts: nagios
  vars_files:
  - vars/global.yml
  pre_tasks:
  - include: private.yml
  roles:
  - role: nagios/nrpe/common
  - role: nagios/head
    nagios_password:        "{{ nagios.secret }}"

- name: playbook | site | Set up nrpe monitoring on all our nodes
  hosts: dynamic
  vars_files:
  - vars/global.yml
  roles:
      - role: nagios/nrpe/common

- name: playbook | site | Set up nrpe website monitoring.
  hosts: nagios
  vars_files:
  - vars/global.yml
  roles:
#  - role: nagios/nrpe/site
#    site: narcissus.rc.rit.edu
#    target: narcissus
#    path: /map/
#  - role: nagios/nrpe/websocket
#    name: narcissus
#    address: "ws://narcissus.rc.rit.edu:9000"
#    topic: http_geojson
#    timeout: 4
  - role: nagios/nrpe/site
    site: threebean.org
    target: widget
    path: /blog/
  - role: nagios/nrpe/site
    site: toscawidgets.org
    target: ZOMG
    path: /
  - role: nagios/nrpe/site
    site: tw2-demos.threebean.org
    target: widget
    path: /
  - role: nagios/nrpe/site
    site: monroe-threebean.rhcloud.com
    target: foreclosures
    path: /graph\?from_date=01%2F01%2F2013\&to_date=01%2F01%2F2013
  - role: nagios/nrpe/site
    site: www.wintonroad.org
    target: experienced
    path: /

- name: playbook | site | Set up bouncer
  hosts: buttermilk
  vars_files:
  - vars/global.yml
  pre_tasks:
  - include: private.yml
  roles:
  - role: irc
    freenode_password:          "{{ freenode.secret }}"
    bitlbee_password:           "{{ bitlbee.secret }}"

- name: playbook | site | Set up computer01 content
  hosts: computer01
  vars_files:
  - vars/global.yml
  pre_tasks:
  - include: private.yml
  roles:
  - role: badges
    db_user:         "{{ tahrir_db_user.secret }}"
    db_password:     "{{ tahrir_db_password.secret }}"
    session_secret:  "{{ tahrir_session_secret.secret }}"
    authn_secret:    "{{ tahrir_authn_secret.secret }}"
  - role: s3backup
    name: tahrir-db
    target: /var/cache/tahrir/tahrir-db.sql
    bucket: threebean-cloud-backup
    s3_aws_backup_access_key:  "{{ aws_backup_access_key.secret }}"
    s3_aws_backup_secret_key:  "{{ aws_backup_secret_key.secret }}"
  - role: nagios/nrpe/site
    site: badges.threebean.net
    target: Tahrir
    path: /
