---
- include: provision.yml
- include: dns.yml

- name: playbook | site | Set up security
  hosts: dynamic
  vars_files:
  - vars/global.yml
  roles:
  - role: security

- name: playbook | site | Set up basic server config
  hosts: dynamic
  vars_files:
  - vars/global.yml
  roles:
  - role: common
  - role: server

- name: playbook | site | Set up nagios head
  hosts: nagios
  vars_files:
  - vars/global.yml
  - vars/private.yml
  roles:
  - role: nagios/nrpe/common
  - role: nagios/head
    nagios_password:        "{{ nagios }}"

- name: playbook | site | Set up nrpe monitoring on all our nodes
  hosts: dynamic
  vars_files:
  - vars/global.yml
  roles:
      - role: nagios/nrpe/common

- name: playbook | site | Set up nrpe website monitoring.
  hosts: nagios
  vars_files:
  - vars/global.yml
  roles:
  - role: nagios/nrpe/site
    site: narcissus.rc.rit.edu
    target: narcissus
    path: /map/
    timeout: 10
  - role: nagios/nrpe/websocket
    name: narcissus
    address: "ws://narcissus.rc.rit.edu:9998"
    topic: http_geojson
    timeout: 4
  - role: nagios/nrpe/site
    site: threebean.org
    target: widget
    path: /blog/
    timeout: 10
  - role: nagios/nrpe/site
    site: toscawidgets.org
    target: ZOMG
    path: /
    timeout: 10
  - role: nagios/nrpe/site
    site: tw2-demos.threebean.org
    target: widget
    path: /
    timeout: 10
  - role: nagios/nrpe/site
    site: monroe-threebean.rhcloud.com
    target: foreclosures
    path: /graph\?from_date=01%2F01%2F2013\&to_date=01%2F01%2F2013
    timeout: 30
  - role: nagios/nrpe/site
    site: www.wintonroad.org
    target: experienced
    path: /
    timeout: 10
  - role: nagios/nrpe/websocket
    name: fedmsg-websocket
    address: "wss://hub.fedoraproject.org:9939"
    timeout: 10

- name: playbook | site | Set up bouncer
  hosts: buttermilk
  vars_files:
  - vars/global.yml
  - vars/private.yml
  roles:
  - irc

- name: playbook | site | Set up computer01 content
  hosts: computer01
  vars_files:
  - vars/global.yml
  - vars/private.yml
  roles:
  - role: badges
    db_user:         "{{ tahrir_db_user }}"
    db_password:     "{{ tahrir_db_password }}"
    session_secret:  "{{ tahrir_session_secret }}"
    authn_secret:    "{{ tahrir_authn_secret }}"
  - role: s3backup
    name: tahrir-db
    target: /var/cache/tahrir/tahrir-db.sql
    bucket: threebean-cloud-backup
    s3_aws_backup_access_key:  "{{ aws_backup_access_key }}"
    s3_aws_backup_secret_key:  "{{ aws_backup_secret_key }}"
  - role: nagios/nrpe/site
    site: badges.threebean.net
    target: Tahrir
    path: /
    timeout: 10
