- name: Install packages
  yum:
      name: "{{item}}"
      state: latest
  with_items:
  - python-narcissus-hub
  - python-narcissus-app
  - libselinux-python
  - python-moksha-hub
  - GeoIP
  tags: narcissus
  notify:
  - restart httpd
  - restart narcissus-hub

- name: Copy over httpd conf file for narcissus wsgi app
  copy:
      src: narcissus.conf
      dest: /etc/httpd/conf.d/narcissus.conf
  tags: narcissus
  notify: restart httpd

- name: Copy over mod_wsgi script for the narcissus app
  copy:
      src: narcissus.wsgi
      dest: /var/www/narcissus.wsgi
  tags: narcissus
  notify: restart httpd

- name: Copy over config file shared by hub and apache
  template:
      src: narcissus.ini
      dest: /etc/narcissus.ini
  tags: narcissus
  notify:
  - restart httpd
  - restart narcissus-hub

- name: Make a directory for moksha config
  file:
      dest: /etc/moksha
      state: directory
  tags: narcissus
  notify:
  - restart httpd
  - restart narcissus-hub

- name: Symlink the config to another name
  file:
      src: /etc/narcissus.ini
      dest: /etc/moksha/production.ini
      state: link
  tags: narcissus
  notify:
  - restart httpd
  - restart narcissus-hub

- name: Copy over narcissus-hub systemd service file
  copy:
      src: narcissus-hub.service
      dest: /usr/lib/systemd/system/narcissus-hub.service
  tags: narcissus
  notify:
  - reload systemd
  - restart narcissus-hub

- name: Update our GeoIP databases from maxmind
  command: geoipupdate
  register: geoipupdate
  changed_when: geoipupdate.rc == 0
  ignore_errors: yes
  tags: narcissus
  notify:
  - restart narcissus-hub

- name: Set the narcissus hub service to start
  service:
      name: narcissus-hub
      state: running
      enabled: yes
  tags: narcissus
