---


- name: system configuration (packages, etc...)
  hosts: geier

  vars_files:
  - vars/global.yml

  roles:
  - common
  - security
  - gnome/system
  - flash
  - jumpoff
  - development
  - task/client
  - role: mail/client
    user: threebean

- name: basics for the gnome user (shortcuts, etc..)
  hosts: geier
  su: yes
  su_user: threebean

  vars_files:
  - vars/global.yml

  roles:
  - gnome/user

# TODO -- two things not covered:
# - ssh config, including the list of proxy commands
# - gpg config, which doesn't really have anything in it anyways
