# requires --extra-vars="target='host1;host2;group etc'

- name: Find whatever is running on port 10319 and storm its figurative bastille.
  hosts: "{{ target }}"
  user: root

  tasks:
  - name: find the PID of whatever is on port 10319
    command: lsof -i :10319 -t
    register: offenders

  - name: salt the earth
    command: "kill {{ item }}"
    with_items: "{{ offenders.stdout_lines }}"
