---
- name: playbook | provision | provision cloud nodes
  hosts: localhost
  connection: local

  # digital ocean creds are kept in the private repo
  vars_files:
  - vars/global.yml
  - {{ private }}/vars.yml

  tasks:
  - include: {{ tasks }}/provision.yml

- name: playbook | provision | setup a local /etc/hosts
  hosts: localhost
  connection: local
  user: root

  vars_files:
  - vars/global.yml

  tasks:
  - include: {{ tasks }}/record_hosts.yml
