# Requires a --extra-vars="target=compute01" option to be passed
---
- name: reboot them all
  hosts: {{target}}
  gather_facts: false

  # digital ocean creds are kept in the private repo
  vars_files:
  - vars/global.yml
  - "{{ private }}/vars.yml"

  tasks:
      - include: reboot
