---
- name: playbook | provision | provision cloud nodes
  hosts: localhost
  connection: local
  gather_facts: false

  # digital ocean creds are kept in the private repo
  vars_files:
  - vars/global.yml
  - $private/vars.yml

  tasks:
  - include: $tasks/provision.yml

- name: playbook | site | Set up security
  hosts: servers

  vars_files:
  - vars/global.yml
  - $private/vars.yml

  roles:
  - $roles/security

- name: playbook | site | Prepare for accelerate mode
  hosts: servers
  tasks:
  - name: Install package required for accelerate mode
    yum: name=python-keyczar state=installed
  - name: Open the ansible accelerate port
    firewalld: >
        port=40319/tcp
        state=enabled
        zone=public
        permanent=false

- name: playbook | site | Set up basic server config
  hosts: servers
  accelerate: true

  vars_files:
  - vars/global.yml
  - $private/vars.yml

  roles:
  - $roles/common
  - $roles/server

- name: playbook | site | Set up nagios head
  hosts: nagios
  accelerate: true

  vars_files:
  - vars/global.yml
  - $private/vars.yml

  roles:
  - $roles/nagios/head

- name: playbook | site | Set up nrpe monitoring on all our nodes
  hosts: servers
  accelerate: true

  vars_files:
  - vars/global.yml
  - $private/vars.yml

  roles:
  - $roles/nagios/nrpe/common

- name: playbook | site | Set up nrpe website monitoring.
  hosts: nagios
  accelerate: true

  vars_files:
  - vars/global.yml
  - $private/vars.yml

  roles:
  - role: $roles/nagios/nrpe/site
    site: narcissus.rc.rit.edu
    target: narcissus
    path: /map/
  - role: $roles/nagios/nrpe/site
    site: threebean.org
    target: widget
    path: /blog/
  - role: $roles/nagios/nrpe/site
    site: tw2-demos.threebean.org
    target: widget
    path: /
  - role: $roles/nagios/nrpe/site
    site: monroe-threebean.rhcloud.com
    target: foreclosures
    path: /graph?from_date=01%2F01%2F2013&to_date=01%2F01%2F2013
  #- role: $roles/nagios/nrpe/site
  # site_fqdn: badges.threebean.org
  # target: threebean
  # path: /

- name: playbook | site | Set up bouncer
  hosts: bouncer
  accelerate: true

  vars_files:
  - vars/global.yml
  - $private/vars.yml

  roles:
  - $roles/irc-bouncer

- name: playbook | site | Set up task server
  hosts: task-server
  accelerate: true

  vars_files:
  - vars/global.yml
  - $private/vars.yml

  roles:
  - $roles/task-server
  - role: $roles/nagios/nrpe/proc
    proc: taskd


# TODO -- nuke this
- name: playbook | site | Set up compute01 content
  hosts: compute01
  accelerate: true

  vars_files:
  - vars/global.yml
  - $private/vars.yml

  roles:
  - $roles/ipython-worker
  - role: $roles/nagios/nrpe/proc
    proc: ipython
