---
- name: playbook | provision | provision cloud nodes
  hosts: localhost
  connection: local
  gather_facts: false

  # digital ocean creds are kept in the private repo
  vars_files:
  - vars/global.yml
  - "{{ private }}/vars.yml"

  tasks:
  - include: "{{ tasks }}/provision.yml"

- name: playbook | site | Set up security
  hosts: dynamic

  vars_files:
  - vars/global.yml
  - "{{ private }}/vars.yml"

  roles:
    - role: "{{ roles }}/security"

  #tasks:
  #- "{{ tasks }}/update-all-packages.yml"

- name: playbook | site | Prepare for accelerate mode
  hosts: dynamic
  tasks:
  - name: Install package required for accelerate mode
    yum: name=python-keyczar state=installed
  - name: Open the ansible accelerate port
    firewalld: >
        port=40319/tcp
        state=enabled
        zone=public
        permanent=false

- name: playbook | site | Set up basic server config
  hosts: dynamic
  accelerate: true

  vars_files:
  - vars/global.yml
  - "{{ private }}/vars.yml"

  roles:
      - role: "{{ roles }}/common"
      - role: "{{ roles }}/server"

- name: playbook | site | Set up nagios head
  hosts: nagios
  accelerate: true

  vars_files:
  - vars/global.yml
  - "{{ private }}/vars.yml"

  roles:
      - role: "{{ roles }}/nagios/head"

- name: playbook | site | Set up nrpe monitoring on all our nodes
  hosts: dynamic
  accelerate: true

  vars_files:
  - vars/global.yml
  - "{{ private }}/vars.yml"

  roles:
      - role: "{{ roles }}/nagios/nrpe/common"

- name: playbook | site | Set up nrpe website monitoring.
  hosts: nagios
  accelerate: true

  vars_files:
  - vars/global.yml
  - "{{ private }}/vars.yml"

  roles:
  - role: "{{ roles }}/nagios/nrpe/site"
    site: narcissus.rc.rit.edu
    target: narcissus
    path: /map/
  - role: "{{ roles }}/nagios/nrpe/site"
    site: threebean.org
    target: widget
    path: /blog/
  - role: "{{ roles }}/nagios/nrpe/site"
    site: tw2-demos.threebean.org
    target: widget
    path: /
  - role: "{{ roles }}/nagios/nrpe/site"
    site: monroe-threebean.rhcloud.com
    target: foreclosures
    path: /graph?from_date=01%2F01%2F2013&to_date=01%2F01%2F2013

- name: playbook | site | Set up bouncer
  hosts: bouncer
  accelerate: true

  vars_files:
  - vars/global.yml
  - "{{ private }}/vars.yml"

  roles:
      - role: "{{ roles }}/irc-bouncer"

- name: playbook | site | Set up task server
  hosts: task-server
  accelerate: true

  vars_files:
      - vars/global.yml
      - "{{ private }}/vars.yml"

  roles:
      - role: "{{ roles }}/task-server"
      - role: "{{ roles }}/nagios/nrpe/proc"
        proc: taskd
        user: taskd

- name: playbook | site | Set up compute01 content
  hosts: compute01
  accelerate: true

  vars_files:
      - vars/global.yml
      - "{{ private }}/vars.yml"

  roles:
      - role: "{{ roles }}/badges"
      - role: "{{ roles }}/nagios/nrpe/site"
        site: badges.threebean.net
        target: Tahrir
        path: /
      # TODO -- nuke this
      - role: "{{ roles }}/ipython-worker"
      - role: "{{ roles }}/nagios/nrpe/proc"
        proc: ipython
        user: ipynb
