---
- name: playbook | provision | provision cloud nodes
  hosts: localhost
  connection: local
  gather_facts: false

  # digital ocean creds are kept in the private repo
  vars_files:
  - vars/global.yml
  - "{{ private }}/vars.yml"

  tasks:
  - debug: msg="talking to digital ocean"
  - include: "{{ tasks }}/provision.yml"
  - name: dns | set up dns for fml.threebean.net
    route53: >
        aws_access_key={{ aws_access_key }}
        aws_secret_key={{ aws_secret_key }}
        command=create
        overwrite=yes
        zone=threebean.net
        record=fml.threebean.net
        type=A
        value={{hostvars.compute01.ansible_ssh_host}}
  - name: dns | set up dns for badges.threebean.net
    route53: >
        aws_access_key={{ aws_access_key }}
        aws_secret_key={{ aws_secret_key }}
        command=create
        overwrite=yes
        zone=threebean.net
        record=badges.threebean.net
        type=A
        value={{hostvars.compute01.ansible_ssh_host}}
  - name: dns | set up dns for tw2-demos.threebean.net
    route53: >
        aws_access_key={{ aws_access_key }}
        aws_secret_key={{ aws_secret_key }}
        command=create
        overwrite=yes
        zone=threebean.net
        record=tw2-demos.threebean.net
        type=A
        value={{hostvars.compute01.ansible_ssh_host}}

- name: playbook | site | Set up security
  hosts: dynamic

  vars_files:
  - vars/global.yml
  - "{{ private }}/vars.yml"

roles:
    - role: security

- name: playbook | site | Prepare for accelerate mode
  hosts: dynamic
  tasks:
  - name: Install package required for accelerate mode
    yum: name={{ item }} state=installed
    with_items:
        - python-keyczar
        - openssl-devel
  - name: Open the ansible accelerate port
    firewalld: >
        port=10319/tcp
        state=enabled
        zone=public
        permanent=true

- name: playbook | site | Set up basic server config
  hosts: dynamic
  accelerate: true

  vars_files:
  - vars/global.yml
  - "{{ private }}/vars.yml"

  roles:
      - role: common
      - role: server

- name: playbook | site | Set up nagios head
  hosts: nagios
  accelerate: true

  vars_files:
  - vars/global.yml
  - "{{ private }}/vars.yml"

  roles:
      - role: nagios/nrpe/common
      - role: nagios/head

- name: playbook | site | Set up nrpe monitoring on all our nodes
  hosts: dynamic
  accelerate: true

  vars_files:
  - vars/global.yml
  - "{{ private }}/vars.yml"

  roles:
      - role: nagios/nrpe/common

- name: playbook | site | Set up nrpe website monitoring.
  hosts: nagios
  accelerate: true

  vars_files:
  - vars/global.yml
  - "{{ private }}/vars.yml"

  roles:
  - role: nagios/nrpe/site
    site: narcissus.rc.rit.edu
    target: narcissus
    path: /map/
  - role: nagios/nrpe/websocket
    name: narcissus
    address: "ws://narcissus.rc.rit.edu:9000"
    topic: http_geojson
    timeout: 4
  - role: nagios/nrpe/site
    site: threebean.org
    target: widget
    path: /blog/
  - role: nagios/nrpe/site
    site: toscawidgets.org
    target: ZOMG
    path: /
  - role: nagios/nrpe/site
    site: tw2-demos.threebean.org
    target: widget
    path: /
  - role: nagios/nrpe/site
    site: monroe-threebean.rhcloud.com
    target: foreclosures
    path: /graph\?from_date=01%2F01%2F2013\&to_date=01%2F01%2F2013
  - role: nagios/nrpe/site
    site: www.wintonroad.org
    target: experienced
    path: /

- name: playbook | site | Set up bouncer
  hosts: buttermilk
  accelerate: true

  vars_files:
  - vars/global.yml
  - "{{ private }}/vars.yml"

  roles:
      - role: irc-bouncer

- name: playbook | site | Set up compute01 content
  hosts: compute01
  accelerate: true

  vars_files:
      - vars/global.yml
      - "{{ private }}/vars.yml"

  roles:
      - role: badges
      - role: s3backup
        name: tahrir-db
        target: /var/cache/tahrir/tahrir-db.sql
        bucket: threebean-cloud-backup
      - role: nagios/nrpe/site
        site: badges.threebean.net
        target: Tahrir
        path: /
