---
- name: playbook | site | provision cloud nodes
  hosts: localhost
  connection: local

  # digital ocean creds are kept in the private repo
  vars_files:
  - vars/global.yml
  - $private/vars.yml

  tasks:

  # Use the digital ocean module to spin up cloud nodes.
  - name: playbook | site | Provision buttermilk if necessary
    digital_ocean: >
      state=active
      name=buttermilk
      ssh_key_ids=threebean
      size_id=66
      region_id=4
      image_id=696598
      wait_timeout=500
      client_id={{ do_client_id }}
      api_key={{ do_api_key }}
      unique_name=true
    register: buttermilk

  - name: Print out node info
    debug: msg={{ buttermilk.droplet.ip_address }}

  - name: playbook | site | add host to dynamic inventory
    add_host: >
        name=buttermilk
        groups=dynamic
        ansible_ssh_host={{ buttermilk.droplet.ip_address }}
        ansible_ssh_user=root


- name: playbook | ipython | setup a local /etc/hosts
  hosts: localhost
  connection: local
  user: root

  vars_files:
  - vars/global.yml

  tasks:
  - name: setup a local etc/hosts
    template: >
        src={{ templates }}/hosts-localhost
        dest=/etc/hosts


- name: playbook | site | Set up buttermilk content and config
  hosts: buttermilk

  vars_files:
  - vars/global.yml
  - $private/vars.yml

  roles:
  - $roles/common
  - $roles/security
  - $roles/server
  - $roles/irc-bouncer
  - $roles/task-server
