---
- name: playbook | provision | provision cloud nodes
  hosts: localhost
  connection: local
  gather_facts: false

  # digital ocean creds are kept in the private repo
  vars_files:
  - vars/global.yml
  - $private/vars.yml

  tasks:
  - include: $tasks/provision.yml

- name: playbook | site | Prepare for accelerate mode
  hosts: servers
  tasks:
  - name: Install package required for accelerate mode
    yum: name=python-keyczar state=installed
  - name: Open the ansible accelerate port
    firewalld: >
        port=40319/tcp
        state=enabled
        zone=public
        permanent=false

- name: playbook | site | Set up basic server config
  hosts: servers
  accelerate: true

  vars_files:
  - vars/global.yml
  - $private/vars.yml

  roles:
  - $roles/security
  - $roles/common
  - $roles/server

- name: playbook | site | Set up nagios head
  hosts: nagios
  accelerate: true

  vars_files:
  - vars/global.yml
  - $private/vars.yml

  roles:
  - $roles/nagios-head

- name: playbook | site | Set up nrpe monitoring on all our nodes
  hosts: servers
  accelerate: true

  vars_files:
  - vars/global.yml
  - $private/vars.yml

  roles:
  - $roles/nagios-nrpe

- name: playbook | site | Set up bouncer
  hosts: bouncer
  accelerate: true

  vars_files:
  - vars/global.yml
  - $private/vars.yml

  roles:
  - $roles/irc-bouncer

- name: playbook | site | Set up task server
  hosts: task-server
  accelerate: true

  vars_files:
  - vars/global.yml
  - $private/vars.yml

  roles:
  - $roles/task-server


# TODO -- nuke this
- name: playbook | site | Set up compute01 content
  hosts: compute01
  accelerate: true

  vars_files:
  - vars/global.yml
  - $private/vars.yml

  roles:
  - $roles/ipython-worker
