---
- name: playbook | provision | provision cloud nodes
  hosts: localhost
  connection: local
  gather_facts: false

  # digital ocean creds are kept in the private repo
  vars_files:
  - vars/global.yml
  - $private/vars.yml

  tasks:
  - include: $tasks/provision.yml

- name: playbook | site | Prepare for accelerate mode
  hosts: buttermilk;compute01
  tasks:
  - name: Install package required for accelerate mode
    yum: name=python-keyczar state=installed

- name: playbook | site | Set up basic server config
  hosts: buttermilk;compute01

  vars_files:
  - vars/global.yml
  - $private/vars.yml

  roles:
  - $roles/security
  - $roles/common
  - $roles/server

- name: playbook | site | Set up buttermilk content
  hosts: buttermilk

  vars_files:
  - vars/global.yml
  - $private/vars.yml

  roles:
  - $roles/irc-bouncer
  - $roles/task-server

- name: playbook | site | Set up compute01 content
  hosts: compute01

  vars_files:
  - vars/global.yml
  - $private/vars.yml

  roles:
  - $roles/ipython-worker
