gpg_gsettings:
  - key: gpg-cache-method
    value: 'timeout'
    schema: org.gnome.crypto.cache

  - key: gpg-cache-ttl
    value: 300
    schema: org.gnome.crypto.cache

standard_keyboard_gsettings:
  - key: clock-show-date
    value: 'true'
    schema: org.gnome.desktop.interface

  - key: clock-format
    value: '12h'
    schema: org.gnome.desktop.interface

  - key: screensaver
    value: "<Primary>BackSpace"
    schema: org.gnome.settings-daemon.plugins.media-keys

  - key: toggle-tiled-left
    value: "[\\'<Alt>h\\']"
    schema: org.gnome.mutter.keybindings

  - key: toggle-tiled-right
    value: "[\\'<Alt>l\\']"
    schema: org.gnome.mutter.keybindings

  - key: toggle-maximized
    value: "[\\'<Alt>k\\']"
    schema: org.gnome.desktop.wm.keybindings

  - key: switch-to-workspace-down
    value: "[\\'<Primary><Alt>j\\']"
    schema: org.gnome.desktop.wm.keybindings

  - key: switch-to-workspace-up
    value: "[\\'<Primary><Alt>k\\']"
    schema: org.gnome.desktop.wm.keybindings

  - key: move-to-workspace-down
    value: "[\\'<Primary><Shift>j\\']"
    schema: org.gnome.desktop.wm.keybindings

  - key: move-to-workspace-up
    value: "[\\'<Primary><Shift>k\\']"
    schema: org.gnome.desktop.wm.keybindings

custom_shortcuts:
- index: custom0
  name: terminal
  command: /usr/bin/gnome-terminal
  binding: '<Primary>Return'

- index: custom1
  name: clip-to-fox
  command: '/home/{{username}}/bin/clip-to-firefox'
  binding: '<Primary>G'

- index: custom2
  name: dagd-clipboard
  command: '/home/{{username}}/bin/dagdclip'
  binding: '<Primary>Space'

- index: custom3
  name: password
  command: '/home/{{username}}/bin/pw-lookup.sh'
  binding: '<Primary>1'

- index: custom4
  name: fas
  command: "'/home/{{username}}/bin/pw-lookup.sh sys/fas'"
  binding: '<Primary>2'

- index: custom5
  name: unfuck-kinesis
  command: "'/usr/bin/xmodmap /home/{{username}}/.xmodmap'"
  binding: '<Primary>F1'

# This is a painfully long list that I would love to be able to generate. Help.
custom_shortcuts_list: "[\\'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/\\',\\'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/\\',\\'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/\\',\\'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/\\',\\'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/\\',\\'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/\\']"
